parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: twpvoice
    database_user: root
    database_password: johnnyB
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 18210810f0137eb184fe692414143b8455
    database_path: null